builds:
-
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  - arm
  goarm:
  - 7
archive:
  replacements:
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Commit }}"
sign:
  artifacts: checksum
dockers:
  -
    image: mhemeryck/modbridge
    goarch: amd64
    goos: linux
    tag_templates:
    - "{{ .Tag }}"
    - "{{ .Arch }}-{{ .Tag }}"
    - "{{ .Arch }}-latest"
    - "{{ .Arch }}"
    - latest
    extra_files:
    - config.yml
