registers:
coils:
- address: 0
  mode: "RW"
  slug: "digital-output-1-1"
- address: 1
  mode: "RW"
  slug: "digital-output-1-2"
- address: 2
  mode: "RW"
  slug: "digital-output-1-3"
- address: 3
  mode: "RW"
  slug: "digital-output-1-4"
- address: 4
  mode: "RW"
  slug: "digital-input-1-1"
- address: 5
  mode: "RW"
  slug: "digital-input-1-2"
- address: 6
  mode: "RW"
  slug: "digital-input-1-3"
- address: 7
  mode: "RW"
  slug: "digital-input-1-4"
- address: 8
  mode: "RW"
  slug: "user-programmable-led-x1"
- address: 9
  mode: "RW"
  slug: "user-programmable-led-x2"
- address: 10
  mode: "RW"
  slug: "user-programmable-led-x3"
- address: 11
  mode: "RW"
  slug: "user-programmable-led-x4"
- address: 1000
  mode: "RW"
  slug: "mwd-reset-indication-reset-of-group-1"
- address: 1001
  mode: "RW"
  slug: "disable-1-wire-bus"
- address: 1002
  mode: "RW"
  slug: "reset-cpu-of-group-1"
- address: 1003
  mode: "RW"
  slug: "save-current-configuration-as-default-to-nv-ram-of-group-1"
- address: 1016
  mode: "RW"
  slug: "enable-ds-on-di-1-1"
- address: 1017
  mode: "RW"
  slug: "enable-ds-on-di-1-2"
- address: 1018
  mode: "RW"
  slug: "enable-ds-on-di-1-3"
- address: 1019
  mode: "RW"
  slug: "enable-ds-on-di-1-4"
- address: 1020
  mode: "RW"
  slug: "enable-ds-polarity-on-di-1-1"
- address: 1021
  mode: "RW"
  slug: "enable-ds-polarity-on-di-1-2"
- address: 1022
  mode: "RW"
  slug: "enable-ds-polarity-on-di-1-3"
- address: 1023
  mode: "RW"
  slug: "enable-ds-polarity-on-di-1-4"
- address: 1024
  mode: "RW"
  slug: "enable-ds-toggle-on-di-1-1"
- address: 1025
  mode: "RW"
  slug: "enable-ds-toggle-on-di-1-2"
- address: 1026
  mode: "RW"
  slug: "enable-ds-toggle-on-di-1-3"
- address: 1027
  mode: "RW"
  slug: "enable-ds-toggle-on-di-1-4"
- address: 100
  mode: "RW"
  slug: "digital-input-2-1"
- address: 101
  mode: "RW"
  slug: "digital-input-2-2"
- address: 102
  mode: "RW"
  slug: "digital-input-2-3"
- address: 103
  mode: "RW"
  slug: "digital-input-2-4"
- address: 100
  mode: "RW"
  slug: "digital-input-2-1"
- address: 101
  mode: "RW"
  slug: "digital-input-2-2"
- address: 102
  mode: "RW"
  slug: "digital-input-2-3"
- address: 103
  mode: "RW"
  slug: "digital-input-2-4"
- address: 104
  mode: "RW"
  slug: "digital-input-2-5"
- address: 105
  mode: "RW"
  slug: "digital-input-2-6"
- address: 106
  mode: "RW"
  slug: "digital-input-2-7"
- address: 107
  mode: "RW"
  slug: "digital-input-2-8"
- address: 108
  mode: "RW"
  slug: "digital-input-2-9"
- address: 109
  mode: "RW"
  slug: "digital-input-2-10"
- address: 110
  mode: "RW"
  slug: "digital-input-2-11"
- address: 111
  mode: "RW"
  slug: "digital-input-2-12"
- address: 112
  mode: "RW"
  slug: "digital-input-2-13"
- address: 113
  mode: "RW"
  slug: "digital-input-2-14"
- address: 114
  mode: "RW"
  slug: "digital-input-2-15"
- address: 115
  mode: "RW"
  slug: "digital-input-2-16"
- address: 116
  mode: "RW"
  slug: "digital-input-2-17"
- address: 117
  mode: "RW"
  slug: "digital-input-2-18"
- address: 118
  mode: "RW"
  slug: "digital-input-2-19"
- address: 119
  mode: "RW"
  slug: "digital-input-2-20"
- address: 120
  mode: "RW"
  slug: "digital-input-2-21"
- address: 121
  mode: "RW"
  slug: "digital-input-2-22"
- address: 122
  mode: "RW"
  slug: "digital-input-2-23"
- address: 123
  mode: "RW"
  slug: "digital-input-2-24"
- address: 124
  mode: "RW"
  slug: "digital-input-2-25"
- address: 125
  mode: "RW"
  slug: "digital-input-2-26"
- address: 126
  mode: "RW"
  slug: "digital-input-2-27"
- address: 127
  mode: "RW"
  slug: "digital-input-2-28"
- address: 128
  mode: "RW"
  slug: "digital-input-2-29"
- address: 129
  mode: "RW"
  slug: "digital-input-2-30"
- address: 1100
  mode: "RW"
  slug: "mwd-reset-indication-reset-of-group-2"
- address: 1102
  mode: "RW"
  slug: "reset-cpu-of-group-2"
- address: 1103
  mode: "RW"
  slug: "save-current-configuration-as-default-to-nv-ram-of-group-2"
- address: 200
  mode: "RW"
  slug: "digital-input-3-1"
- address: 201
  mode: "RW"
  slug: "digital-input-3-2"
- address: 202
  mode: "RW"
  slug: "digital-input-3-3"
- address: 203
  mode: "RW"
  slug: "digital-input-3-4"
- address: 204
  mode: "RW"
  slug: "digital-input-3-5"
- address: 205
  mode: "RW"
  slug: "digital-input-3-6"
- address: 206
  mode: "RW"
  slug: "digital-input-3-7"
- address: 207
  mode: "RW"
  slug: "digital-input-3-8"
- address: 208
  mode: "RW"
  slug: "digital-input-3-9"
- address: 209
  mode: "RW"
  slug: "digital-input-3-10"
- address: 210
  mode: "RW"
  slug: "digital-input-3-11"
- address: 211
  mode: "RW"
  slug: "digital-input-3-12"
- address: 212
  mode: "RW"
  slug: "digital-input-3-13"
- address: 213
  mode: "RW"
  slug: "digital-input-3-14"
- address: 214
  mode: "RW"
  slug: "digital-input-3-15"
- address: 215
  mode: "RW"
  slug: "digital-input-3-16"
- address: 216
  mode: "RW"
  slug: "digital-input-3-17"
- address: 217
  mode: "RW"
  slug: "digital-input-3-18"
- address: 218
  mode: "RW"
  slug: "digital-input-3-19"
- address: 219
  mode: "RW"
  slug: "digital-input-3-20"
- address: 220
  mode: "RW"
  slug: "digital-input-3-21"
- address: 221
  mode: "RW"
  slug: "digital-input-3-22"
- address: 222
  mode: "RW"
  slug: "digital-input-3-23"
- address: 223
  mode: "RW"
  slug: "digital-input-3-24"
- address: 224
  mode: "RW"
  slug: "digital-input-3-25"
- address: 225
  mode: "RW"
  slug: "digital-input-3-26"
- address: 226
  mode: "RW"
  slug: "digital-input-3-27"
- address: 227
  mode: "RW"
  slug: "digital-input-3-28"
- address: 228
  mode: "RW"
  slug: "digital-input-3-29"
- address: 229
  mode: "RW"
  slug: "digital-input-3-30"
- address: 1200
  mode: "RW"
  slug: "mwd-reset-indication-reset-of-group-3"
- address: 1202
  mode: "RW"
  slug: "reset-cpu-of-group-3"
- address: 1203
  mode: "RW"
  slug: "save-current-configuration-as-default-to-nv-ram-of-group-3"
mqtt_broker_uri: "tcp://raspberrypi.lan:1883"
mqtt_client_id: "modbridge"
modbus_server_uri: "unipi.lan:502"
