[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "github.com/goburrow/modbus"
  version = "0.1.0"
